#IN Dev
[Host]
ssh_host=3.111.118.247
ssh_user=centos
ssh_password=3mWZ3BhdVFQDOjG4MKWy
mysql_host=india-api-dev.ck0p8hows6ib.ap-south-1.rds.amazonaws.com
mysql_user=okusr
mysql_password=3mWZ3BhdVFQDOjG4MKWy
mysql_database=okdatabase
packageid=com.ind.kyc.application:id/
XPATH = /hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/

#登入頁
[login]
phone_no= 9999999777
otp = 000000
policy = Privacy Policy