[basic]
package=ind.kaarban.credit.iciu:id/
phone_no =9999999888
APP_NAME=Dev IN API
#訪客首頁
[uncertified_homepage]
Welcome=Welcome
Get_my_limit=Get my limit
Agree=Agree
#payment
[payment]
There_are_no_orders_currently= There are no orders currently
Payment_Details= Payment Details
Payment_Details1=Order No.
Payment_Details2=Loan Date
Payment_Details3=Due Date
Payment_Details4=Repayment Amount
Payment_Details5=Apply Date
[customer_email]
email =App:${AppVariable}\nName:${NameVariable}\nPhone:${PhoneVariable}
app_INDEV=Dev IN API
email2=1244843@gmail.com
google_play=發生錯誤
#客服-FEEDBACK選單
[customer_FEEDBACK]
Feedback_Categories=Feedback Categories
Order_Issues_message=Please provide detailed information about your order problem:\n．Product Name:\n．Order Number:\n．Issue Description:
Received_Feedback=Thank you for taking the time to provide your feedback. We will take it into careful consideration and will respond to your feedback as quickly as possible.
Authentication_Issuess_message=Please explain the authentication problem you are facing:\n．Login Email/Username:\n．Detailed Description of the Issue:
Product_Issues=Please provide detailed information about the product issue:\n．Product Name:\n．Issue Description:
Loan_Issues=Please explain the loan problem you are facing:\n．Order Number:\n．Detailed Description of the Issue:
Repayment_Issues=Please explain the repayment problem you are facing:\n．Order Number:\n．Repayment Amount:\n．Detailed Description of the Issue:
Card_Binding_Issues=Please provide detailed information about the card binding issue:\n．Card Type (Bankcard/E-wallet):\n．Detailed Description of the Issue:
System_Issues=Please provide detailed information about the system issue:\n．Error Message (if applicable):\n．Detailed Description of the Issue:
Others=Please explain the other issue you are facing:\n．Detailed Description of the Issue:
#客服-FEEDBACK預設文字
Feedback=Feedback
#優惠券
[coupon]
There_are_currently_no_coupons=There are currently no coupons
#刪除訊息預設文字
[Delete]
Phone_Number=Phone Number
#刪除訊息錯誤訊息
Delete_Wrong_message=Please double-check the number you entered as it does not match the registered number.
Delete_Wrong_message2=Please enter the correct phone number.
#刪除訊息送出
Delete_confirm_message=This account no longer exists.\nIt will take 7 days for the account to be completely deleted.\nIf you need to log in again, please wait until the deletion is complete.\n\nHope to see you again!
#log out文案
[log_out]
Log_out=Log out
Log_out_message=Are you sure you want to exit application?
#let's go start權限文案
[lets_go]
title=Let’s Get Started
camera_access=⦿ allow camera access
SMS_access=⦿ allow SMS access
bluetooth_access=⦿ allow bluetooth access
calendar_access=⦿ allow calendar access
location_access=⦿ allow location access
#認證彈窗
[certified]
certified_back_message=You have not completed the certification information, and will lose the obtained increase limit and coupons. Are you sure you want to quit?
#Personal Information
[certified_per]
Personal_title=Personal Information
select=select
Enter_your_email=Enter your email
optional_Wrong_message=please choose an option
enter_Wrong_message=This field cannot be left blank.
enter_Wrong_message2=please enter the data with correct email format
Salary_Range=₹0 - ₹15000
Marital_Status=unmarried
Job_Position=Ordinary staff
Education=No education
#Emergency Contacts
[certified_CONTEC]
select_relationship=select relationship
select_from_the_contacts=select from the contacts
relationship_Wrong_message=Please select an option
Phone_Number_Wrong_message=Please enter a phone number without any spaces or special characters.
Phone_Number_Wrong_message2=please enter different number
relationship_Father=Father
relationship_Relatives=Relatives
relationship_Colleague=Colleague
relationship_Friend=Friend
Phone_Number=Phone Number
enter_Wrong_message=This field cannot be left blank
[certified_QA]
select=select
N0=No
[certified_ID]
pan_front=PAN Front
face_photo=Position your face in the frame and click the capture button to take a photo.
confirm=Confirm
Title=ID Proof
Title2=PAN card details
field_ID=Please fill in ID of PAN card.
field_NAME=Please fill in name of PAN card.
field_birthday=Please fill in birthday of PAN Card.
field_father_name=Please fill in father name of PAN card.
enter_Wrong_message=This field cannot be left blank.
enter_Wrong_message2=Invalid format. Please enter again
enter_Wrong_message3=Your age is outside the allowed range for application. Please choose your birthday again.
gender1=Male
gender2=Female
[certified_BK]
UPI=Your UPI ID is unique and usually follows the format
enter_Wrong_message4=Account number must be between from 9 to 18 digits only.
enter_Wrong_message5=Please make sure your account number match.
enter_Wrong_message6=The IFSC code must consist of 11 characters. Please ensure that you have entered the correct format.
enter_Wrong_message7=Invalid UPI ID format. Please retry or refer to the provided instructions and try again.
[product_DT]
DT1=terms
DT2=Disbursal Amount
DT3=Due Date
Loan_Agreement=Online Personal Loan Agreement
Loan_Orders=Loan Orders
Completed_certification=Completed certification
Star=Tap a Star to Rate
Star_popup=Thank you!
[certified_homepage]
Time=Exclusive Personal Loan offer
Processing=Processing
L1_title1=Your application was not approved
L1_title2=We regret to inform you that we cannot offer you any loans due to your credit score being below our standards.\n\nIf you have any questions, please contact our customer service center.
L1_banner=Borrow now for discounts, get certified immediately to earn the discounts.
L1_slot=₹ ****/ ****
L1_staus=Application progress
L2_title1=Under review
L2_title2=Your submitted order has been successfully received. \n\nPlease wait patiently for review.
L3_title1=Your application was not approved
L3_title2=Sorry, we regret to inform you that your loan application did not meet approval criteria.\n\nIf you have any questions, please contact our customer service center.
L3_title3=Welcome back and reapply in
L3_banner=Borrow now to get discounts.
L3_1_title1=Application Denied
L3_1_title2=We regret to inform you that your application has been denied due to your current credit score not meeting the requirements. \n\nWe kindly request you to try again later.
L4_title1=Oops...
L4_title2=We are sorry that there are currently no suitable options to recommend to you. \n\nIf you have any questions, please contact our customer service center.
L7_title1=Tips
L7_title2=Your current preferential loan quota has been used up.\n\nRemind you to prioritize repayment to obtain a higher credit limit, and wait for the next round of preferential loan plans.
L7_slot=₹ 0 / 0
L9_title2=There are currently no products available for borrowing. Please return after countdown ends.
L10_title=Recommended Products
L10_Apply1=Authorization
Loan_Agreement=Loan Agreement
Successful_Application=Successful Application
L5_banner=You still have an unrepaid loan. To prevent your rights from being affected, please repay as soon as possible.
L5_title=Remind you to prioritize paying off overdue payments before you can borrow again.
L6_banner=Please note that any request for prepayment is a scam.
[Permissions1]
element1 = SMS
element2 = Calendar
element3 = Location
element4 = AppList
[Permissions2]
element1 = location
element2 = SMS
element3 = calendar
element4 = bluetooth

