#basic_IND DEV
[basic]
packageid=com.ind.kyc.application:id/
XPATH = /hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/


#訪客首頁
[texts]
welcome = Welcome
exit = Leave
stay = Stay on this page 
maximum_text = Maximum Loan Amount up to
advertising_amount = ₹ 80,000
get = Get my limit
account = Account
loan = loan
payment = payment
Privacy = Privacy Policy
Disclosure = Disclosure statement



#登入頁
[login]
phone_no= 9999999777
otp = 000000
policy = Privacy Policy

