#IN Dev 
[IND_dev]
ssh_host=3.111.118.247
ssh_user=centos
ssh_password=3mWZ3BhdVFQDOjG4MKWy
mysql_host=india-api-dev.ck0p8hows6ib.ap-south-1.rds.amazonaws.com
mysql_user=okusr
mysql_password=3mWZ3BhdVFQDOjG4MKWy
mysql_database=okdatabase

